### ISSUE TITLE
Bootstrap step, Key Error

### ISSUE THREAD

**Issue by jiangzy26** [sculab/GeneMiner#2]
Hi, I am trying the method to extract phylogenetic markers from NGS data, but an Error occurred from my data or your test dataset, could you share your help? Thank you very much. 
Below is the output:
$ python3 /data2/software-use/GeneMiner/geneminer.py \
> -1 /data2/software-use/GeneMiner-geneminer_v1.1/DEMO/skimming_data1.fq.gz \
> -2 /data2/software-use/GeneMiner-geneminer_v1.1/DEMO/skimming_data2.fq.gz \
> -rtfa /data2/software-use/GeneMiner-geneminer_v1.1/DEMO/shallow_ref/ITS.fasta \
> -t 10 -bn 20  -o test.result
----------------------
GeneMiner: a software for extracting phylogenetic markers from next generation sequencing data
Version: 1.1
Copyright (C) 2023 Pulin Xie & Y.YU
Project name          :/data2/my/result/1-geneminer/test.result
Data1                 :/data2/software-use/geneminer-geneminer_v1.1/demo/skimming_data1.fq.gz
Data2                 :/data2/software-use/geneminer-geneminer_v1.1/demo/skimming_data2.fq.gz
Reference (fa)        :/data2/software-use/geneminer-geneminer_v1.1/demo/shallow_ref/its.fasta
K1                    :31
K2                    :41
Threads               :10
Re-filtering          :1
Step length           :4
Limit count           :2
Limit min ratio       :0.9
Limit max ratio       :2.0
Change seed           :32
Max length            :5000
Min length            :0
Soft boundary         :0
Data size             :all
Bootstrap             :yes
Bootstrap number      :20
----------------------
========================== Filter ==========================
Hashdict has prepared
Memory of hashdict:0.0023G
Filter time used: 6.44s
======================== Re-Filter =========================
Re-Filter time used: 0.00s
========================= Assemble =========================
ITS best_seed: GATACTTG... best_length: 702 ref_length: 678
Assembly reads time used: 0.30s

======================== Bootstrap =========================
Using GeneMiner...
Preparing bootstrap data:   1/1
Traceback (most recent call last):
  File "/data2/software-use/GeneMiner/geneminer.py", line 308, in <module>
    main(args)
  File "/data2/software-use/GeneMiner/geneminer.py", line 198, in main
    my_bootstrap_pipeline_main(configuration_information)
  File "/data2/software-use/GeneMiner/lib/bootstrap_pipeline.py", line 511, in my_bootstrap_pipeline_main
    my_bootstrap_pipeline.bootstrap_filter()
  File "/data2/software-use/GeneMiner/lib/bootstrap_pipeline.py", line 369, in bootstrap_filter
    my_filter_main(filter_configuration_information)
  File "/data2/software-use/GeneMiner/lib/my_filter.py", line 799, in my_filter_main
    re_filter=configuration_information["re_filter"]
              ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 're_filter'

**Comment by sculab** [comment]
Sorry, we fixed that bug a long time ago, but we forgot to update it in the release. Please clone GeneMiner's repository from github or download release v1.1.1
